-- ============================================================
-- MCW Clinician Matcher — add 5 clinicians found in the master
-- Google Sheet but missing from the app (2026-07-29).
-- Safe to run twice: 'on conflict do nothing' skips existing ids.
-- ============================================================

insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority, active) values ('stephen_rochon', 'Stephen Rochon', 'Stephen Rochon, RMHCI', 'therapy', '["DTSP"]'::jsonb, false, 185, null, 200, 200, 'Tues, Thurs, Fri', '["Minors", "Couples", "Families", "Individuals"]'::jsonb, '["CBT", "DBT", "EFT", "Art Therapy", "Gottman Couples Therapy", "Mindfulness-Based Therapy"]'::jsonb, '["Anxiety", "Depression", "Grief", "Trauma", "BPD", "OCD", "Eating Disorders", "Body Image", "Self-esteem", "ADHD", "Substance Abuse/Addiction", "Divorce/Separation", "Self-harm", "Suicidal Ideation", "Mens Issues", "Communication", "Career Development"]'::jsonb, 'Min age 5. Also works with couples/family, communication, and career development.', 'Needs Clients', 'Medium Priority', true)
on conflict (id) do nothing;

insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority, active) values ('levi_draper', 'Levi Draper', 'Levi Draper, RMHCI', 'therapy', '["Tampa"]'::jsonb, false, 150, null, null, 200, 'Mon-Fri', '["Minors", "Families", "Individuals"]'::jsonb, '["CBT", "EMDR", "DBT", "ACT", "EFT", "Art Therapy", "Mindfulness-Based Therapy", "Walk and Talk Therapy", "Existential-Humanistic"]'::jsonb, '["Anxiety", "Depression", "Grief", "Trauma", "BPD", "OCD", "Self-esteem", "ADHD", "ASD", "Substance Abuse/Addiction", "LGBTQIA+", "Self-harm", "Suicidal Ideation", "Womens Issues", "Mens Issues", "Anger Management", "Stress Management", "Faith-Based Counseling", "Personality Issues"]'::jsonb, 'Min age 10 (younger OK within family therapy; prefers teens 13+). Not yet taking couples.', 'Accepting', 'Medium Priority', true)
on conflict (id) do nothing;

insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority, active) values ('judy_franks', 'Judy Franks', 'Judy Franks, RSCWI', 'therapy', '["Sarasota"]'::jsonb, false, null, '$100-$150 (sliding scale)', null, null, 'Wed-Fri', '["Minors", "Couples", "Individuals"]'::jsonb, '["CBT", "EMDR", "DBT", "ACT", "EFT", "Art Therapy", "Mindfulness-Based Therapy", "Walk and Talk Therapy"]'::jsonb, '["Anxiety", "Depression", "Grief", "Trauma", "Self-esteem", "ADHD", "Womens Issues"]'::jsonb, 'Sliding scale: individual $100-$150, couples $175-$200. Min age 14.', 'Needs Clients', 'High Priority', true)
on conflict (id) do nothing;

insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority, active) values ('lisa_smotherman', 'Lisa Smotherman', 'Lisa Smotherman, APRN, PMHNP-BC', 'psychiatry', '["Sarasota", "Virtual"]'::jsonb, true, null, '$195 follow-up / $390 eval', null, null, 'Wednesday and Thursday, virtual and in-person', '["Minors", "Individuals"]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Insurance: Aetna, Ascension Health, Carelon Behavioral Health (fka Beacon Health), Cigna, Oscar (Optum), Oxford (Optum). Adolescents and adults 18-64. Prefers minors 13+.', 'Needs Clients', 'High Priority', true)
on conflict (id) do nothing;

insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority, active) values ('christine_farina', 'Christine Farina', 'Christine Farina, APRN, PMHNP-BC', 'psychiatry', '["DTSP", "Virtual"]'::jsonb, true, null, '$195 follow-up / $390 eval', null, null, 'Schedule TBD - contact office', '["Individuals"]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Insurance: Aetna, Ascension Health, Carelon Behavioral Health (fka Beacon Health), Cigna. Adults only.', 'Needs Clients', 'High Priority', true)
on conflict (id) do nothing;
