const STORAGE_KEY = "mcw_matcher_v4";
const LOGIN_PASSWORD = "mcw2025"; // used ONLY in local mode (when SUPABASE_URL below is empty)

// --- Supabase shared backend ---
// Paste the project's values here to switch the app from per-browser localStorage
// to the shared database with real per-staff logins. Leave empty for local-only mode.
// The anon key is designed to be public — access is enforced server-side by RLS.
const SUPABASE_URL = "https://gazzhqtqnmpyjejwujei.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_3yqQgb_zZJ_LaCdbMxHlbg_uaJ0OwzC";

const SEED_DATA = [
  { id:"kiesa", name:"Kiesa DeSimone", profile:"Kiesa DeSimone, LMHC", type:"therapy", offices:["Tyrone"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Fri", accepting:"Needs Clients", priority:"High Priority", groups:["Minors","Individuals"], modalities:["CBT","EMDR","DBT","ACT","EFT","Mindfulness-Based Therapy","Walk and Talk Therapy","Somatic"], specialties:["Anxiety","Depression","Grief","Trauma","Bipolar","Body Image","Self-esteem","ASD","Abuse/DV","LGBTQIA+","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Mens Issues","Substance Abuse/Addiction"], notes:"Prefers clients with trauma history. Strong with complex trauma." },
  { id:"sarah", name:"Sarah Drew", profile:"Sarah Drew, LMHC", type:"therapy", offices:["DTSP"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Fri", accepting:"Needs Clients", priority:"Medium Priority", groups:["Minors","Individuals"], modalities:["CBT","DBT","Mindfulness-Based Therapy","Person Centered","Gestalt","Narrative","REBT"], specialties:["Anxiety","Depression","Self-esteem","Womens Issues","Trauma","LGBTQIA+","Grief","Bipolar"], notes:"" },
  { id:"madison", name:"Madison Magnus", profile:"Madison Magnus, LMHC", type:"therapy", offices:["DTSP"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Thurs in-person, Fri telehealth", accepting:"Needs Clients", priority:"High Priority", groups:["Minors","Individuals"], modalities:["CBT","ACT","EFT","Art Therapy","Mindfulness-Based Therapy","Walk and Talk Therapy","EMDR"], specialties:["Anxiety","Depression","Grief","Trauma","Self-esteem"], notes:"Prefers teens and 20s. No couples. Prefers not older adults." },
  { id:"aimee", name:"Aimee Yasin", profile:"Aimee Yasin, LMHC", type:"therapy", offices:["Sarasota"], virtual:false, indiv:185, couples:235, family:235, schedule:"Mon-Wed", accepting:"Needs Clients", priority:"High Priority", groups:["Couples","Families","Minors","Individuals"], modalities:["CBT","DBT","Gottman Couples Therapy","Mindfulness-Based Therapy","TFCBT","Reality Therapy","IFS"], specialties:["Anxiety","Depression","Grief","Trauma","BPD","LGBTQIA+","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Mens Issues","Self-esteem","Anger Management"], notes:"Enjoys high-acuity clients. No 5pm new patient slots." },
  { id:"kelly", name:"Kelly Lehman (Virtual Only)", profile:"Kelly Lehman, LMHC", type:"therapy", offices:["Tyrone","DTSP","Sarasota","Tampa"], virtual:true, indiv:185, couples:235, family:235, schedule:"Mon-Sat", accepting:"Needs Clients", priority:"Medium Priority", groups:["Couples","Families","Individuals"], modalities:["CBT","DBT","ACT","EFT","Gottman Couples Therapy","Mindfulness-Based Therapy","Somatic","IFS"], specialties:["Anxiety","Depression","Grief","Trauma","Body Image","Eating Disorders","OCD","Self-esteem","Divorce/Separation","Womens Issues","Mens Issues","Military","Medical Trauma"], notes:"VIRTUAL ONLY. Loves couples, grief, C-PTSD, young adults. Eating disorders from age 10." },
  { id:"nicole", name:"Nicole Wilson", profile:"Nicole Wilson, LMHC", type:"therapy", offices:["DTSP"], virtual:false, indiv:185, couples:235, family:null, schedule:"Mon-Fri", accepting:"Not Accepting", priority:"Medium Priority", groups:["Couples","Individuals"], modalities:["EMDR","ART","Walk and Talk Therapy","Gottman Couples Therapy","RLT","Brainspotting"], specialties:["Anxiety","Trauma","Divorce/Separation","Womens Issues"], notes:"No couples unless client specifically requests her — check with Nicole first. Does intensives." },
  { id:"emily_t", name:"Emily Tripp", profile:"Emily Tripp, LMHC", type:"therapy", offices:["DTSP"], virtual:false, indiv:185, couples:235, family:null, schedule:"Mon-Wed in-person, Thurs telehealth", accepting:"Not Accepting", priority:"High Priority", groups:["Minors","Couples","Individuals"], modalities:["CBT","EMDR","DBT","Art Therapy","ACT","Gottman Couples Therapy","Mindfulness-Based Therapy","Walk and Talk Therapy","Gestalt/Somatic","Narrative","Music Therapy"], specialties:["Anxiety","Depression","Grief","Trauma","Bipolar","Body Image","Self-esteem","ADHD","Substance Abuse/Addiction","LGBTQIA+","Womens Issues","Suicidal Ideation"], notes:"NO BPD, severe psychopathology, high-conflict divorce. Bipolar must be medicated." },
  { id:"bjorn", name:"Bjorn Nagle", profile:"Bjorn Nagle, LMHC", type:"therapy", offices:["DTSP"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Fri", accepting:"Needs Clients", priority:"Medium Priority", groups:["Individuals"], modalities:["CBT","DBT","Mindfulness-Based Therapy","Walk and Talk Therapy","Enneagram"], specialties:["Anxiety","Depression","Body Image","Self-esteem","Divorce/Separation","Mens Issues","Life Transitions","Spirituality"], notes:"Adults only." },
  { id:"shea", name:"Shea Dickey", profile:"Shea Dickey, RCSWI", type:"therapy", offices:["Tampa"], virtual:false, indiv:185, couples:235, family:null, schedule:"Mon-Thurs", accepting:"Needs Clients", priority:"High Priority", groups:["Couples","Minors","Individuals"], modalities:["CBT","DBT","EFT","Mindfulness-Based Therapy","Walk and Talk Therapy"], specialties:["Anxiety","Depression","Body Image","Self-esteem","Grief","LGBTQIA+","Womens Issues","Self-harm"], notes:"Strong with women post-relationship, low self-esteem, attachment work." },
  { id:"emily_c", name:"Emily Camera", profile:"Emily Camera, LCSW", type:"therapy", offices:["Tyrone"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Thurs", accepting:"Needs Clients", priority:"Medium Priority", groups:["Minors","Individuals"], modalities:["DBT","ART","ACT","Mindfulness-Based Therapy","Walk and Talk Therapy"], specialties:["Anxiety","Trauma","Bipolar","BPD","Body Image","Self-esteem","LGBTQIA+","Abuse/DV","Self-harm","Womens Issues","Depression","Identity Formation"], notes:"Polyamory/kink-aware. Min age 16." },
  { id:"soula", name:"Soula Hareas (Virtual Only)", profile:"Soula Hareas, LMHC", type:"therapy", offices:["Tyrone","DTSP","Sarasota","Tampa"], virtual:true, indiv:185, couples:235, family:235, schedule:"Mon-Thurs", accepting:"Needs Clients", priority:"Low Priority", groups:["Families","Couples","Minors","Individuals"], modalities:["CBT","Art Therapy","Gottman Couples Therapy","DBT","TFCBT"], specialties:["Anxiety","Grief","Trauma","Bipolar","ADHD","LGBTQIA+","Abuse/DV","Divorce/Separation","Womens Issues","Mens Issues","Self-esteem","Life Transitions","Premarital"], notes:"VIRTUAL ONLY. Life transitions, premarital, infidelity, culture/ethnicity." },
  { id:"carolyn", name:"Carolyn McNulty", profile:"Carolyn McNulty, LMHC", type:"therapy", offices:["DTSP"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Thurs", accepting:"Accepting", priority:"Medium Priority", groups:["Individuals"], modalities:["CBT","Mindfulness-Based Therapy","Walk and Talk Therapy","Holistic"], specialties:["Anxiety","Grief","Self-esteem","Divorce/Separation","Womens Issues","Mens Issues"], notes:"NO PERSONALITY DISORDERS. Prefers 18+." },
  { id:"brittany", name:"Brittany Hoff", profile:"Brittany Hoff, LMHC", type:"therapy", offices:["Sarasota"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Thurs", accepting:"Needs Clients", priority:"High Priority", groups:["Individuals"], modalities:["CBT","DBT","Mindfulness-Based Therapy","Walk and Talk Therapy","EMDR"], specialties:["Anxiety","Depression","Trauma","Grief","Bipolar","Body Image","Self-esteem","Substance Abuse/Addiction","ADHD","LGBTQIA+","Abuse/DV","Divorce/Separation","Womens Issues","Mens Issues","Suicidal Ideation","Self-harm","OCD"], notes:"No 4pm or 5pm for new patient slots." },
  { id:"joy", name:"Joy Laurila", profile:"Joy Laurila, LCSW", type:"therapy", offices:["Tyrone"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Fri", accepting:"Accepting", priority:"High Priority", groups:["Minors","Individuals"], modalities:["CBT","DBT","Mindfulness-Based Therapy","Walk and Talk Therapy","CBT-E","CBT-AR","ERP"], specialties:["Anxiety","Depression","Grief","Trauma","Bipolar","BPD","OCD","Eating Disorders","Body Image","Self-esteem","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues"], notes:"Eating disorder specialist. Sees families for eating disorders ONLY (FBT)." },
  { id:"rachel", name:"Rachel DeStefano", profile:"Rachel DeStefano, LMFT, LMHC", type:"therapy", offices:["Tyrone"], virtual:false, indiv:185, couples:235, family:225, schedule:"Mon-Wed and Fri", accepting:"Not Accepting", priority:"High Priority", groups:["Couples","Families","Individuals"], modalities:["CBT","ART","REBT","Psychodrama","Experiential"], specialties:["Anxiety","Grief","Trauma","Self-esteem","Substance Abuse/Addiction","Divorce/Separation","Womens Issues","Postpartum","Motherhood"], notes:"" },
  { id:"ashe", name:"Ashe Sullivan", profile:"Ashe Sullivan, LMHC", type:"therapy", offices:["Tampa"], virtual:false, indiv:185, couples:null, family:235, schedule:"Mon-Fri", accepting:"Needs Clients", priority:"High Priority", groups:["Minors","Families","Individuals"], modalities:["CBT","DBT","Mindfulness-Based Therapy","Walk and Talk Therapy","Polyvagal Therapy"], specialties:["Depression","Anxiety","Grief","Trauma","OCD","Eating Disorders","Body Image","Self-esteem","ADHD","ASD","Substance Abuse/Addiction","LGBTQIA+","Abuse/DV","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Mens Issues","Maternal Health"], notes:"Experienced with high-risk suicidal ideation and LGBTQ+ issues. Min age 6." },
  { id:"alyssa", name:"Alyssa Merryman", profile:"Alyssa Merryman, RMHCI", type:"therapy", offices:["Tyrone"], virtual:false, indivDisplay:"$100-$150 (sliding scale)", couples:null, family:null, schedule:"Mon, Tues, Thurs", accepting:"Needs Clients", priority:"Low Priority", groups:["Minors","Individuals"], modalities:["CBT","DBT","Art Therapy","Mindfulness-Based Therapy"], specialties:["Anxiety","Depression","OCD","Body Image","Self-esteem","ADHD"], notes:"Sliding scale $100-$150. Prefers adolescents and young adults. Min age 10." },
  { id:"kevin", name:"Kevin Curtin", profile:"Kevin Curtin, RMHCI", type:"therapy", offices:["Tyrone"], virtual:false, indiv:185, couples:235, family:null, schedule:"Mon-Sat", accepting:"Accepting", priority:"High Priority", groups:["Minors","Couples","Individuals"], modalities:["CBT","DBT","Art Therapy","Mindfulness-Based Therapy","Psychodynamic","Existential-Humanistic","Narrative","Movement/Flow Therapy"], specialties:["Anxiety","Depression","BPD","OCD","Bipolar","Self-esteem","ADHD","Substance Abuse/Addiction","Mens Issues","Grief","Spirituality","Sports Psychology"], notes:"Works best with creative/overthinker types. Min age 12." },
  { id:"jasmine", name:"Jasmine Klugh", profile:"Jasmine Klugh, LCSW", type:"therapy", offices:["Sarasota"], virtual:false, indiv:185, couples:235, family:235, schedule:"Tues-Fri", accepting:"Accepting", priority:"High Priority", groups:["Minors","Couples","Families","Individuals"], modalities:["CBT","Walk and Talk Therapy"], specialties:["Anxiety","Depression","Bipolar","Body Image","Self-esteem","ADHD","ASD","Divorce/Separation","Suicidal Ideation","Self-harm","Womens Issues","School Issues","Sports Performance"], notes:"Min age 4." },
  { id:"christopher", name:"Christopher Rhodes", profile:"Christopher Rhodes, LMHC", type:"therapy", offices:["Tampa"], virtual:false, indiv:185, couples:235, family:null, schedule:"Mon-Fri", accepting:"Needs Clients", priority:"High Priority", groups:["Couples","Minors","Individuals"], modalities:["CBT","DBT","Gottman Couples Therapy","Mindfulness-Based Therapy","Positive Psychology","Person Centered Therapy"], specialties:["Anxiety","Depression","Trauma","Self-esteem","LGBTQIA+","Divorce/Separation","Mens Issues","Grief","Sexual Dysfunction","Midlife Crisis"], notes:"Open to most clients. Above are preferences. Min age 16." },
  { id:"albena", name:"Albena Christova", profile:"Albena Christova, LMHC", type:"therapy", offices:["Tyrone"], virtual:false, indiv:185, couples:235, family:235, schedule:"Mon-Fri", accepting:"Accepting", priority:"High Priority", groups:["Couples","Families","Individuals"], modalities:["CBT","Walk and Talk Therapy","Solution Focused Therapy"], specialties:["Anxiety","Depression","Self-esteem","Bipolar","Divorce/Separation","Womens Issues","Stress Management","Life Transitions"], notes:"" },
  { id:"amanda", name:"Amanda Glatthaar", profile:"Amanda Glatthaar, RMHCI", type:"therapy", offices:["DTSP"], virtual:false, indiv:185, couples:null, family:null, schedule:"Mon-Fri", accepting:"Needs Clients", priority:"High Priority", groups:["Individuals"], modalities:["CBT","DBT","ACT","Walk and Talk Therapy","Psychodynamic"], specialties:["Anxiety","Depression","Grief","Bipolar","BPD","Self-esteem","Substance Abuse/Addiction","LGBTQIA+","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Trauma","Infertility"], notes:"Sliding scale available ($150). Open to most clients." },
  { id:"anna", name:"Anna Kitsos", profile:"Anna Kitsos, LMHC", type:"therapy", offices:["DTSP"], virtual:false, indiv:185, couples:235, family:235, schedule:"Mon-Fri", accepting:"Needs Clients", priority:"Medium Priority", groups:["Couples","Families"], modalities:["CBT","DBT","ACT","EFT","Mindfulness-Based Therapy","Walk and Talk Therapy","Motivational Interviewing","Attachment-Based Therapy","Psychodynamic","Polyvagal","TF-CBT","IFS"], specialties:["Anxiety","Depression","Trauma","Bipolar","BPD","Self-esteem","Substance Abuse/Addiction","Abuse/DV","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Childhood Trauma"], notes:"Sliding scale available." },
  { id:"jamilah", name:"Jamilah Tulloch", profile:"Jamilah Tulloch, PMHNP, BC", type:"psychiatry", offices:["Virtual"], virtual:true, indivDisplay:"$195 follow-up / $390 eval", couples:null, family:null, schedule:"Sat-Mon", accepting:"Accepting", priority:"Low Priority", groups:["Individuals"], modalities:[], specialties:[], notes:"Insurance: Aetna, Cigna, United, BCBS MA, Carelon, Oscar, Oxford, UHC, Horizon BCBS NJ, Independence BCBS PA. Adults only. No Substance Abuse Disorder. No Schizophrenia. VIRTUAL ONLY." },
  { id:"amy", name:"Amy Wiley", profile:"Amy Wiley, APRN, PMHNP-BC", type:"psychiatry", offices:["Virtual"], virtual:true, indivDisplay:"$195 follow-up / $390 eval", couples:null, family:null, schedule:"Tues-Fri", accepting:"Needs Clients", priority:"High Priority", groups:["Individuals"], modalities:[], specialties:[], notes:"Insurance: Aetna, Cigna, United, BCBS MA, Carelon, Oscar, Oxford, UHC, Horizon BCBS NJ, Independence BCBS PA. Adults only. No Substance Abuse Disorder. No Schizophrenia. VIRTUAL ONLY." },
  { id:"lena", name:"Lena Allos", profile:"Lena Allos, PMHNP", type:"psychiatry", offices:["Tyrone","Virtual"], virtual:true, indivDisplay:"$195 follow-up / $390 eval", couples:null, family:null, schedule:"Mon virtual, Tues virtual & in-person (Tyrone)", accepting:"Needs Clients", priority:"High Priority", groups:["Individuals"], modalities:[], specialties:[], notes:"Insurance: Aetna, Cigna. Sees children 6+. Tuesdays in-office at Tyrone." },
];

const PRIORITY_ORDER = { "High Priority": 0, "Medium Priority": 1, "Low Priority": 2 };
const STATUS_ORDER = { "Accepting": 0, "Needs Clients": 1, "Not Accepting": 2 };
