// ============================================================
// MCW Clinician Matcher — in-app help content
// One dictionary powering BOTH the ⓘ popovers and the "? Help" panel,
// so the two can never disagree. Plain English for non-technical staff.
// Loaded before script.js; exposes the global HELP + HELP_GROUPS.
// ============================================================

const HELP = {
  "search": {
    title: "Search box",
    what: "One box that searches most of what is written on a clinician's card.",
    how: "Type any part of a name, credentials, specialty, modality, session type, office, or the yellow admin note. The list narrows as you type, and part-words work — \"anx\" finds Anxiety, \"gott\" finds Gottman.",
    tip: "It does not search the days worked or the rates, and it only looks inside the tab you are on. If someone is missing, check the other Provider type tab.",
  },
  "provider-type": {
    title: "Therapy and Psychiatry tabs",
    what: "Two separate lists. Therapy is counsellors, Psychiatry is prescribers, and you only ever see one at a time.",
    how: "Click therapy or psychiatry. The count, the cards and the filters below all follow this choice.",
    tip: "Switching to psychiatry unticks any Specialty and Modality boxes and hides both sections, because psychiatry providers are not tagged that way. \"Clear all filters\" does not bring you back to therapy — click the tab yourself.",
  },
  "session-type": {
    title: "Session type boxes",
    what: "Shows only clinicians who see that kind of client: Individual, Couples, Family or Minors.",
    how: "Tick what the client actually needs. These boxes stack strictly — Couples and Minors together shows only people who do both. The Office boxes just above work the other way: Tampa and Tyrone shows everyone at either one.",
    tip: "This reads the clinician's session groups, not their rates. Someone you know does couples can still be hidden if \"Couples\" was never ticked on their record, and 🩺 Health flags exactly that.",
  },
  "specialty-modality": {
    title: "Specialty and Modality lists",
    what: "Specialty is what the client is dealing with — Anxiety, Trauma, OCD. Modality is how the clinician works — CBT, EMDR, Gottman.",
    how: "Tick one or more. Ticking several shows anyone who matches at least one, so more ticks widens the list rather than narrowing it. Use the small Search box above each list to jump to an entry instead of scrolling, and the \"Clear\" link under a list to untick that list only.",
    tip: "Both sections exist on the Therapy tab only. The lists are built from what has been typed onto clinicians' cards, so an entry with no results means nobody has it listed — not that the filter is broken.",
  },
  "filter-chips": {
    title: "Filters you have switched on",
    what: "One pill for each Specialty (green) and Modality (blue) you have ticked. They show you why the list is as short as it is.",
    how: "Click the × on a pill to drop that one filter and widen the list, leaving the rest of your search alone.",
    tip: "Only specialties and modalities get a pill. Your search text, the office and session-type ticks and the Therapy/Psychiatry tab are not shown here. \"Clear all filters\" wipes all of those, but leaves you on the same tab and the same sort.",
  },
  "sort": {
    title: "How the list is ordered",
    what: "\"Priority + Availability\" puts High Priority first, then Medium, then Low. Inside each of those it puts Accepting first, then Needs Clients, then Not Accepting, and ties go A–Z by name.",
    how: "Leave it on Priority + Availability while you are matching a client. Switch to Name A–Z to find one specific person, or Office when you are filling one location.",
    tip: "The top card is not always bookable. A High Priority clinician who is Not Accepting still sits above a Medium Priority one who is Accepting, so read the badges before you offer anyone.",
  },
  "card-anatomy": {
    title: "What's on a card",
    what: "The colour bar and the two badges on the right are priority and availability. Under the name come the offices, then the days worked, the rates and the session types, then modalities and specialties.",
    how: "Read the yellow note box, if there is one, before you offer anyone an appointment. The buttons along the bottom copy the card or open it for editing.",
    tip: "The count only covers the tab you are on, and never counts deactivated people, so it is normally smaller than the whole practice.",
  },
  "someone-is-missing": {
    title: "Someone I know is missing",
    what: "Almost always a filter, not a fault. Nobody satisfies all of your ticks at the same time.",
    how: "Click \"Clear filters\", or untick one box at a time until people reappear. Check you are on the right Therapy/Psychiatry tab.",
    tip: "Still gone? They may have been deactivated. Anyone with editing rights can look at the bottom of ⚙ Update all clinicians and click Reactivate.",
  },
  "availability-badge": {
    title: "Is this clinician taking clients?",
    what: "Green Accepting means they have room. Amber Needs Clients means they have room and especially want referrals. Red Not Accepting means do not book new clients with them.",
    how: "Book into Accepting and Needs Clients. Treat Not Accepting as closed, and check with a supervisor before making any exception.",
    tip: "This is the most time-sensitive thing on the card. The moment a clinician takes their last slot, update it from \"Edit status & priority\" so nobody double-books them.",
  },
  "priority-badge": {
    title: "What priority means",
    what: "How badly the practice wants this clinician's caseload filled. It is not a rating of the clinician and nothing to do with how urgent the client is.",
    how: "When two clinicians fit the client equally well, send the client to the higher-priority one. The colour bar across the top of the card says the same thing: red is High, amber is Medium, blue is Low.",
    tip: "Priority comes from the practice's Google Sheet. Changing it on a card lasts only until the next pull from the sheet — see \"Sync from Sheet\".",
  },
  "rates-row": {
    title: "Session rates",
    what: "The self-pay price per session. Some clinicians show words instead of a number, such as \"$100-$150 (sliding scale)\".",
    how: "Quote these when a client asks what it costs.",
    tip: "A missing rate does not prove they do not offer that session type — the 👥 line decides that. If the whole money line is missing, no rates are on file at all; tell an admin.",
  },
  "specs-more": {
    title: "Hidden specialties",
    what: "Cards show only the first five specialties so they stay short. \"+7 more\" means seven others are hidden behind it.",
    how: "Click it to see them all, and \"show less\" to fold them away again.",
    tip: "Never assume a clinician does not treat something because you cannot see it. The Specialty list in the sidebar and the search box always look at the full list, hidden tags included.",
  },
  "admin-note": {
    title: "The yellow note box",
    what: "Internal instructions from the practice about who this clinician should and should not get: minimum ages, hard no's, and rules like \"no 4pm or 5pm new patient slots\".",
    how: "Read it before every referral. It overrides the rest of the card — someone can list Trauma and still have a note saying they will not take that case.",
    tip: "This is internal. Never read it out to a client or paste it anywhere they will see, and never put a client's name or any clinical detail into it.",
    role: "Everyone can read it. Front Desk and above can change it.",
  },
  "copy-card": {
    title: "Copy the card as text",
    what: "Puts the whole card on your clipboard as plain text: name, offices, availability, priority, days, rates, session types, specialties, modalities and the note.",
    how: "Click it — the button flashes \"✓ Copied\" — then paste into an email, the EHR, or a message to a colleague.",
    tip: "It includes the internal note. Delete that line before anything goes to a client. If your browser blocks copying, a small box appears with the text so you can copy it by hand.",
    role: "Everyone can use this, including Viewers.",
  },
  "which-edit-button": {
    title: "Which edit button?",
    what: "\"Edit status & priority\" changes the three things that move every day: availability, priority and the yellow note. \"Edit details\" opens the full form — name, offices, days, rates, session types — plus Deactivate and Delete.",
    how: "Use the first one after a call, the moment a clinician fills or frees a slot. Use the second only for things that rarely change, like a new office or a rate.",
    tip: "Saving either one goes live on every other screen within seconds. Cancel throws your changes away.",
    role: "\"Edit status & priority\" needs Front Desk or above. \"Edit details\" is Admin and Owner only.",
  },
  "update-all": {
    title: "Update several people at once",
    what: "One long panel with availability, priority and notes for every active clinician, split into Therapists and Psychiatry.",
    how: "Use it for a weekly sweep: scroll through, change the few people whose status moved, then click Save all changes at the bottom.",
    tip: "Nothing saves as you type — Cancel, the ×, or the Esc key loses everything on the screen. Only the rows you actually changed get written, so you cannot wipe out a colleague's edit.",
    role: "Front Desk, Admin and Owner. Viewers do not see this button.",
  },
  "deactivated-section": {
    title: "Where hidden people live",
    what: "Everyone who has been deactivated. They are invisible on the normal list, but nothing about them has been lost.",
    how: "Click Reactivate next to a name and they come straight back onto every screen.",
    role: "Front Desk, Admin and Owner.",
  },
  "add-specialty": {
    title: "Adding a new specialty",
    what: "Creates a specialty that does not exist anywhere in the practice yet, and ticks it for this clinician.",
    how: "Type it and press Enter, or click Add. It appears ticked in the list above. Nothing is kept until you click Save.",
    tip: "Read the list first. Typos and near-duplicates — \"Trauma\" and \"trauma work\" — become permanent options in everyone's sidebar, and tidying them up later means editing each clinician by hand.",
    role: "Front Desk and above for the picker on a card; Admin and Owner for the Edit details form.",
  },
  "mods-picker": {
    title: "Editing modalities",
    what: "The methods this clinician practises — EMDR, CBT, DBT, Gottman. They are what the sidebar Modality list filters on.",
    how: "Click the ✕ beside one to take it off, type a new one in the box below and press Enter to add it, then click Save modalities.",
    tip: "Unlike specialties there is no master list to tick from, so your spelling creates the filter entry. \"EMDR\" and \"E.M.D.R.\" become two separate entries and clients get missed — copy the spelling from another clinician's card.",
    role: "Front Desk and above.",
  },
  "add-clinician": {
    title: "Add a clinician",
    what: "Opens a blank form that creates a clinician everyone in the practice will see.",
    how: "Fill in name, profile, provider type, days, offices, session groups and rates, then click Add clinician. New people start as Needs Clients / Medium Priority with no specialties — add those from their card afterwards.",
    tip: "Two things are easy to forget. Tick every session group they offer, or the Session type boxes will hide them. And add them to the Google Sheet using the id on their Edit details screen, or every pull from the sheet will skip them.",
    role: "Admin and Owner only.",
  },
  "editor-name": {
    title: "Name, with no credentials",
    what: "The person's plain name — \"Jane Doe\". Credentials go in the Profile box next to it.",
    how: "Type first and last name. The form will not save without it.",
    tip: "On a brand-new clinician this also creates their permanent id for the Google Sheet — \"Jane Doe\" becomes jane_doe — so get the spelling right the first time. Renaming them later does not change the id.",
    role: "Admin and Owner only.",
  },
  "editor-offices": {
    title: "Offices and telehealth",
    what: "The places this clinician sees clients. These ticks are what the sidebar Office boxes match on.",
    how: "Tick every office they cover, not only their main one; at least one is required. Tick \"Offers telehealth (virtual)\" as well for anyone who does video sessions.",
    tip: "Telehealth is a label, not a location — it adds a grey \"Virtual\" tag and puts them in no Office filter. Someone whose only tick is the Virtual office box disappears the moment anyone uses an Office box, so tick the real offices they serve too.",
    role: "Admin and Owner only.",
  },
  "editor-session-groups": {
    title: "Session groups",
    what: "Who this clinician will see: Individuals, Couples, Families, Minors. This is the one thing the sidebar Session type boxes read.",
    how: "Tick every kind of client they take. At least one is required.",
    tip: "Leave a box unticked and that clinician vanishes the second anyone filters by that session type. The rates below have no effect on this.",
    role: "Admin and Owner only.",
  },
  "editor-rates": {
    title: "Rates",
    what: "What a session costs. The three ($) boxes take digits only — 185, not \"$185/session\". Leave any of them blank if there is no set price.",
    how: "For a sliding scale, or anything a single number cannot say, use \"…or rate as text\" instead: \"$100-$150 (sliding scale)\".",
    tip: "Fill in both the Individual number and the text box and the card shows the text and hides the number. Anything that is not a plain positive number is refused when you save, and the red box at the top of the form says so.",
    role: "Admin and Owner only.",
  },
  "editor-save": {
    title: "What this button does not save",
    what: "Saves the details on this form — name, profile, type, days, offices, session groups, rates, specialties and modalities — for every member of staff.",
    how: "Click once and wait; it reads \"Saving…\" while it works.",
    tip: "Availability, priority and the yellow note are not on this form. They live on the card, under \"Edit status & priority\".",
    role: "Admin and Owner only.",
  },
  "deactivate-vs-delete": {
    title: "Deactivate, not Delete",
    what: "Deactivate hides someone from every screen and keeps all their information. Delete erases them for everyone, forever.",
    how: "Use Deactivate whenever someone goes on leave or leaves the practice. Keep Delete for a genuine mistake, like a duplicate you created a minute ago.",
    tip: "Deactivate can be undone at the bottom of ⚙ Update all clinicians. Delete cannot be undone by anyone, and you have to confirm it twice.",
    role: "Deactivate: Admin and Owner. Delete: Owner only.",
  },
  "sheet-sync": {
    title: "Sync from Sheet",
    what: "Priority and availability are set in the practice's Google Sheet. This pulls the latest values now and shows you exactly what changed.",
    how: "Click it after someone edits the sheet. It also runs on its own every time you sign in.",
    tip: "The sheet wins. A priority you change on a card is replaced at the next pull, so for a lasting change edit the sheet. Google takes about five minutes to publish a sheet edit — wait a moment before you try again.",
    role: "Front Desk, Admin and Owner. Viewers do not see this button.",
  },
  "sheet-id": {
    title: "Their id for the sheet",
    what: "The permanent code name this clinician has in the system. It is how a row in the Google Sheet finds the right person.",
    how: "Copy it into the id column of the sheet when you add someone new. Until you do, the sheet cannot manage their priority.",
    tip: "It never changes, even if their name does, and two clinicians can share a first name. Never retype an id from memory, and never edit the id column in the sheet.",
    role: "Shown on Edit details, so Admin and Owner only.",
  },
  "sheet-report": {
    title: "What the sheet just changed",
    what: "A receipt for the last pull from the Google Sheet. \"Updated from sheet\" lists everyone whose priority or availability it changed.",
    how: "Skim it to confirm your sheet edit landed. It opens when you click ⟳ Sync from Sheet, and appears on its own after an automatic pull only when something went wrong. A grey list at the bottom names people who have no row in the sheet at all — they were left alone.",
    tip: "This is where manual edits get overwritten. If a priority you set in the app earlier is listed here with a different value, the sheet has replaced it.",
    role: "Front Desk, Admin and Owner.",
  },
  "sheet-report-problems": {
    title: "Two problems only the sheet can fix",
    what: "Red means a cell the app could not understand, usually a misspelling like \"Hgih\". Amber means a row whose id belongs to nobody — a mistyped id, or someone who has been removed from the app.",
    how: "Fix the spelling, or correct or delete the row, in the Google Sheet. Then click ⟳ Sync from Sheet again.",
    tip: "Nothing was guessed and nobody was changed for these rows. Priority takes High, Medium or Low; availability takes Accepting, Needs Clients or Not Accepting.",
    role: "Front Desk, Admin and Owner.",
  },
  "your-role": {
    title: "What you are allowed to do",
    what: "Your role decides which buttons appear. Viewer: read only. Front Desk: availability, priority, notes, specialties, modalities. Admin: also add and edit clinicians and manage logins. Owner: also delete.",
    how: "Check this line first when a button someone described is not on your screen. Your role is the reason, not a broken page.",
    tip: "If an admin has just changed your role, this line will not catch up until you sign out and back in.",
    role: "Everyone sees this line; the wording changes with your role.",
  },
  "health": {
    title: "Health check",
    what: "A one-click scan of the list for problems: duplicate ids, missing names or days, values that would sort wrongly, and mismatches that quietly hide someone from the filters.",
    how: "Click it any time and work down the list. Red errors are actually broken, amber warnings usually mean someone is being hidden from searches, blue notes are just worth knowing.",
    tip: "It only reports; it never changes anything, so it is safe to run mid-call. Fix what it finds on the clinician's card or in Edit details, then run it again. Deactivated people are skipped.",
    role: "Everyone can run this, including Viewers.",
  },
  "export": {
    title: "Download a snapshot",
    what: "Saves the whole list to a file named with today's date, as a record. It changes nothing.",
    how: "Click it and the file lands in your Downloads folder. Useful before a big tidy-up, or when someone wants an offline copy.",
    tip: "The file holds rates and internal notes, so treat it as confidential. It cannot be loaded back in — the live information lives in the shared database.",
    role: "Front Desk, Admin and Owner. Viewers do not see this button.",
  },
  "invite-role": {
    title: "Which role should I pick?",
    what: "The role decides what the new person can change. From least to most: Viewer, Front Desk, Admin, Owner.",
    how: "Viewer can look but change nothing. Front Desk does the daily work — availability, priority, notes, specialties, modalities. Admin also adds and edits clinicians and manages logins; Owner can also delete a clinician for good.",
    tip: "When in doubt pick Front Desk. It covers everything a scheduler does on the phone, cannot damage the list, and can be raised later in two clicks. The limits are enforced by the database, not only by hidden buttons.",
    role: "As an Admin you can only offer Front Desk and Viewer. Only the Owner can make someone an Admin, and nobody can create a second Owner here.",
  },
  "send-invite": {
    title: "Inviting someone",
    what: "Creates the account and emails that person a link to set their own password. You never see or set it.",
    how: "Type their work email — that address becomes their username — pick a role, then click once and wait for the green \"Invite sent to…\" line. They then appear in the list below.",
    tip: "If you get a message about the team-management function not being deployed, nobody was emailed and no account was made. Ask the practice owner to create it from the Supabase dashboard; changing existing people's roles still works.",
    role: "Admin and Owner only.",
  },
  "change-role": {
    title: "Changing someone's role",
    what: "Changes what that person can do. It saves the moment you pick a new value — there is no Save button.",
    how: "Pick the new role. If it does not stick you get a pop-up and the list reloads, so you can see everyone's real role.",
    tip: "The change only reaches that person when they next sign in or reload the page. If access has to stop right now, set them to Viewer and ask them to sign out and back in.",
    role: "As an Admin you can only set Front Desk or Viewer.",
  },
  "remove-person": {
    title: "Removing someone",
    what: "Deletes that person's login. They can no longer sign in on any device.",
    how: "Click Remove and confirm. Use it when someone leaves the practice.",
    tip: "Nothing they entered is lost — notes, priorities and the whole clinician list stay put. If Remove gives an error, set them to Viewer instead: that blocks all editing until an owner can finish the job.",
    role: "Admin and Owner only.",
  },
  "team-list": {
    title: "Who can sign in",
    what: "Everyone with a login, sorted by access level: Owner first, then Admins, Front Desk, then Viewers.",
    how: "Each row shows the person's email and a coloured role tag, with a dropdown to change their role and a Remove button.",
    tip: "If audit-bot@mcnultycounseling.com appears here, leave it alone — that is the automated nightly checker, not a person.",
    role: "Admin and Owner only.",
  },
  "owner-row": {
    title: "Why this row is locked",
    what: "The Owner's account has no role dropdown and no Remove button. It cannot be changed from inside the app.",
    how: "Nothing to do here. If the Owner's access ever has to change, it is done in the practice's Supabase account.",
    tip: "This is deliberate. It stops anyone, including an Admin, from locking the practice out of its own system.",
    role: "Admin and Owner only.",
  },
  "no-self-signup": {
    title: "Why there is no sign-up",
    what: "Accounts are only created by an Admin or the Owner. There is no way to register yourself, and that is on purpose.",
    how: "Ask the practice owner or an admin to invite you from 👥 Manage team, then watch your work email for the invite.",
    tip: "The list holds rates, availability and internal notes. If sign-up were open, anyone who found the web address could read all of it.",
  },
  "forgot-password": {
    title: "Forgot your password",
    what: "Emails you a link so you can pick a new password yourself, without asking anyone.",
    how: "Click it, type your work email, click \"Send reset link\", then open the email and follow the link. It brings you back here to choose a new password.",
    tip: "The message says \"if that email has an account\" even when it does not; that is a safety measure, not a fault. Check your spam folder the first time, and do not press the button repeatedly — the practice can only send a couple of reset emails an hour.",
  },
  "new-password": {
    title: "Choosing a new password",
    what: "The screen you land on after following the link in your email.",
    how: "Type the same new password into both boxes and click Save. You go straight into the app; you do not sign in again.",
    tip: "It needs at least 8 characters and the two boxes must match. Cancel throws the reset away and signs you out, so you would have to ask for a new email.",
  },
  "two-people-editing": {
    title: "Two of you editing at once",
    what: "Different parts of a clinician cannot clash. Details, status, specialties and modalities are each saved on their own.",
    how: "Carry on. For the same box, the last save wins, and every screen updates live so you will see it happen.",
  },
  "page-out-of-date": {
    title: "The page looks out of date",
    what: "Your browser is showing an old copy of the app.",
    how: "Refresh the hard way once: Ctrl+Shift+R on Windows, or Cmd+Shift+R on a Mac.",
  },
};

// Order + grouping for the Help panel index.
const HELP_GROUPS = [
  { group: "Finding a clinician", keys: ["search", "provider-type", "session-type", "specialty-modality", "filter-chips", "sort", "card-anatomy", "someone-is-missing"] },
  { group: "Reading a card", keys: ["availability-badge", "priority-badge", "rates-row", "specs-more", "admin-note", "copy-card", "which-edit-button"] },
  { group: "Updating clinicians", keys: ["update-all", "deactivated-section", "add-specialty", "mods-picker", "add-clinician", "editor-name", "editor-offices", "editor-session-groups", "editor-rates", "editor-save", "deactivate-vs-delete", "two-people-editing"] },
  { group: "The Google Sheet", keys: ["sheet-sync", "sheet-id", "sheet-report", "sheet-report-problems"] },
  { group: "Team & access", keys: ["your-role", "invite-role", "send-invite", "change-role", "remove-person", "team-list", "owner-row", "no-self-signup", "forgot-password", "new-password"] },
  { group: "Tools & troubleshooting", keys: ["health", "export", "page-out-of-date"] },
];

if (typeof module !== "undefined") { module.exports = { HELP, HELP_GROUPS }; }
