-- ============================================================
-- MCW Clinician Matcher — Supabase one-time setup
-- Paste this WHOLE file into the Supabase SQL Editor and click Run.
-- Generated from data.js SEED_DATA (26 clinicians).
-- ============================================================

-- 1) Table
create table if not exists public.clinicians (
  id text primary key,
  name text not null,
  profile text,
  type text not null default 'therapy',
  offices jsonb not null default '[]'::jsonb,
  virtual boolean not null default false,
  indiv numeric,
  "indivDisplay" text,
  couples numeric,
  family numeric,
  schedule text,
  groups jsonb not null default '[]'::jsonb,
  modalities jsonb not null default '[]'::jsonb,
  specialties jsonb not null default '[]'::jsonb,
  notes text not null default '',
  accepting text not null default 'Needs Clients',
  priority text not null default 'Medium Priority',
  updated_at timestamptz not null default now()
);

-- 2) Keep updated_at fresh on every change
create or replace function public.set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists clinicians_updated_at on public.clinicians;
create trigger clinicians_updated_at
  before update on public.clinicians
  for each row execute function public.set_updated_at();

-- 3) Row Level Security: only signed-in staff can read or write.
alter table public.clinicians enable row level security;

drop policy if exists "staff can read" on public.clinicians;
create policy "staff can read" on public.clinicians
  for select to authenticated using (true);

drop policy if exists "staff can update" on public.clinicians;
create policy "staff can update" on public.clinicians
  for update to authenticated using (true) with check (true);

drop policy if exists "staff can insert" on public.clinicians;
create policy "staff can insert" on public.clinicians
  for insert to authenticated with check (true);

drop policy if exists "staff can delete" on public.clinicians;
create policy "staff can delete" on public.clinicians
  for delete to authenticated using (true);

-- 4) Live sync between staff screens
alter publication supabase_realtime add table public.clinicians;

-- 5) Seed the roster (one-time)
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('kiesa', 'Kiesa DeSimone', 'Kiesa DeSimone, LMHC', 'therapy', '["Tyrone"]'::jsonb, false, 185, null, null, null, 'Mon-Fri', '["Minors","Individuals"]'::jsonb, '["CBT","EMDR","DBT","ACT","EFT","Mindfulness-Based Therapy","Walk and Talk Therapy","Somatic"]'::jsonb, '["Anxiety","Depression","Grief","Trauma","Bipolar","Body Image","Self-esteem","ASD","Abuse/DV","LGBTQIA+","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Mens Issues","Substance Abuse/Addiction"]'::jsonb, 'Prefers clients with trauma history. Strong with complex trauma.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('sarah', 'Sarah Drew', 'Sarah Drew, LMHC', 'therapy', '["DTSP"]'::jsonb, false, 185, null, null, null, 'Mon-Fri', '["Minors","Individuals"]'::jsonb, '["CBT","DBT","Mindfulness-Based Therapy","Person Centered","Gestalt","Narrative","REBT"]'::jsonb, '["Anxiety","Depression","Self-esteem","Womens Issues","Trauma","LGBTQIA+","Grief","Bipolar"]'::jsonb, '', 'Needs Clients', 'Medium Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('madison', 'Madison Magnus', 'Madison Magnus, LMHC', 'therapy', '["DTSP"]'::jsonb, false, 185, null, null, null, 'Mon-Thurs in-person, Fri telehealth', '["Minors","Individuals"]'::jsonb, '["CBT","ACT","EFT","Art Therapy","Mindfulness-Based Therapy","Walk and Talk Therapy","EMDR"]'::jsonb, '["Anxiety","Depression","Grief","Trauma","Self-esteem"]'::jsonb, 'Prefers teens and 20s. No couples. Prefers not older adults.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('aimee', 'Aimee Yasin', 'Aimee Yasin, LMHC', 'therapy', '["Sarasota"]'::jsonb, false, 185, null, 235, 235, 'Mon-Wed', '["Couples","Families","Minors","Individuals"]'::jsonb, '["CBT","DBT","Gottman Couples Therapy","Mindfulness-Based Therapy","TFCBT","Reality Therapy","IFS"]'::jsonb, '["Anxiety","Depression","Grief","Trauma","BPD","LGBTQIA+","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Mens Issues","Self-esteem","Anger Management"]'::jsonb, 'Enjoys high-acuity clients. No 5pm new patient slots.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('kelly', 'Kelly Lehman (Virtual Only)', 'Kelly Lehman, LMHC', 'therapy', '["Tyrone","DTSP","Sarasota","Tampa"]'::jsonb, true, 185, null, 235, 235, 'Mon-Sat', '["Couples","Families","Individuals"]'::jsonb, '["CBT","DBT","ACT","EFT","Gottman Couples Therapy","Mindfulness-Based Therapy","Somatic","IFS"]'::jsonb, '["Anxiety","Depression","Grief","Trauma","Body Image","Eating Disorders","OCD","Self-esteem","Divorce/Separation","Womens Issues","Mens Issues","Military","Medical Trauma"]'::jsonb, 'VIRTUAL ONLY. Loves couples, grief, C-PTSD, young adults. Eating disorders from age 10.', 'Needs Clients', 'Medium Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('nicole', 'Nicole Wilson', 'Nicole Wilson, LMHC', 'therapy', '["DTSP"]'::jsonb, false, 185, null, 235, null, 'Mon-Fri', '["Couples","Individuals"]'::jsonb, '["EMDR","ART","Walk and Talk Therapy","Gottman Couples Therapy","RLT","Brainspotting"]'::jsonb, '["Anxiety","Trauma","Divorce/Separation","Womens Issues"]'::jsonb, 'No couples unless client specifically requests her — check with Nicole first. Does intensives.', 'Not Accepting', 'Medium Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('emily_t', 'Emily Tripp', 'Emily Tripp, LMHC', 'therapy', '["DTSP"]'::jsonb, false, 185, null, 235, null, 'Mon-Wed in-person, Thurs telehealth', '["Minors","Couples","Individuals"]'::jsonb, '["CBT","EMDR","DBT","Art Therapy","ACT","Gottman Couples Therapy","Mindfulness-Based Therapy","Walk and Talk Therapy","Gestalt/Somatic","Narrative","Music Therapy"]'::jsonb, '["Anxiety","Depression","Grief","Trauma","Bipolar","Body Image","Self-esteem","ADHD","Substance Abuse/Addiction","LGBTQIA+","Womens Issues","Suicidal Ideation"]'::jsonb, 'NO BPD, severe psychopathology, high-conflict divorce. Bipolar must be medicated.', 'Not Accepting', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('bjorn', 'Bjorn Nagle', 'Bjorn Nagle, LMHC', 'therapy', '["DTSP"]'::jsonb, false, 185, null, null, null, 'Mon-Fri', '["Individuals"]'::jsonb, '["CBT","DBT","Mindfulness-Based Therapy","Walk and Talk Therapy","Enneagram"]'::jsonb, '["Anxiety","Depression","Body Image","Self-esteem","Divorce/Separation","Mens Issues","Life Transitions","Spirituality"]'::jsonb, 'Adults only.', 'Needs Clients', 'Medium Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('shea', 'Shea Dickey', 'Shea Dickey, RCSWI', 'therapy', '["Tampa"]'::jsonb, false, 185, null, 235, null, 'Mon-Thurs', '["Couples","Minors","Individuals"]'::jsonb, '["CBT","DBT","EFT","Mindfulness-Based Therapy","Walk and Talk Therapy"]'::jsonb, '["Anxiety","Depression","Body Image","Self-esteem","Grief","LGBTQIA+","Womens Issues","Self-harm"]'::jsonb, 'Strong with women post-relationship, low self-esteem, attachment work.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('emily_c', 'Emily Camera', 'Emily Camera, LCSW', 'therapy', '["Tyrone"]'::jsonb, false, 185, null, null, null, 'Mon-Thurs', '["Minors","Individuals"]'::jsonb, '["DBT","ART","ACT","Mindfulness-Based Therapy","Walk and Talk Therapy"]'::jsonb, '["Anxiety","Trauma","Bipolar","BPD","Body Image","Self-esteem","LGBTQIA+","Abuse/DV","Self-harm","Womens Issues","Depression","Identity Formation"]'::jsonb, 'Polyamory/kink-aware. Min age 16.', 'Needs Clients', 'Medium Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('soula', 'Soula Hareas (Virtual Only)', 'Soula Hareas, LMHC', 'therapy', '["Tyrone","DTSP","Sarasota","Tampa"]'::jsonb, true, 185, null, 235, 235, 'Mon-Thurs', '["Families","Couples","Minors","Individuals"]'::jsonb, '["CBT","Art Therapy","Gottman Couples Therapy","DBT","TFCBT"]'::jsonb, '["Anxiety","Grief","Trauma","Bipolar","ADHD","LGBTQIA+","Abuse/DV","Divorce/Separation","Womens Issues","Mens Issues","Self-esteem","Life Transitions","Premarital"]'::jsonb, 'VIRTUAL ONLY. Life transitions, premarital, infidelity, culture/ethnicity.', 'Needs Clients', 'Low Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('carolyn', 'Carolyn McNulty', 'Carolyn McNulty, LMHC', 'therapy', '["DTSP"]'::jsonb, false, 185, null, null, null, 'Mon-Thurs', '["Individuals"]'::jsonb, '["CBT","Mindfulness-Based Therapy","Walk and Talk Therapy","Holistic"]'::jsonb, '["Anxiety","Grief","Self-esteem","Divorce/Separation","Womens Issues","Mens Issues"]'::jsonb, 'NO PERSONALITY DISORDERS. Prefers 18+.', 'Accepting', 'Medium Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('brittany', 'Brittany Hoff', 'Brittany Hoff, LMHC', 'therapy', '["Sarasota"]'::jsonb, false, 185, null, null, null, 'Mon-Thurs', '["Individuals"]'::jsonb, '["CBT","DBT","Mindfulness-Based Therapy","Walk and Talk Therapy","EMDR"]'::jsonb, '["Anxiety","Depression","Trauma","Grief","Bipolar","Body Image","Self-esteem","Substance Abuse/Addiction","ADHD","LGBTQIA+","Abuse/DV","Divorce/Separation","Womens Issues","Mens Issues","Suicidal Ideation","Self-harm","OCD"]'::jsonb, 'No 4pm or 5pm for new patient slots.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('joy', 'Joy Laurila', 'Joy Laurila, LCSW', 'therapy', '["Tyrone"]'::jsonb, false, 185, null, null, null, 'Mon-Fri', '["Minors","Individuals"]'::jsonb, '["CBT","DBT","Mindfulness-Based Therapy","Walk and Talk Therapy","CBT-E","CBT-AR","ERP"]'::jsonb, '["Anxiety","Depression","Grief","Trauma","Bipolar","BPD","OCD","Eating Disorders","Body Image","Self-esteem","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues"]'::jsonb, 'Eating disorder specialist. Sees families for eating disorders ONLY (FBT).', 'Accepting', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('rachel', 'Rachel DeStefano', 'Rachel DeStefano, LMFT, LMHC', 'therapy', '["Tyrone"]'::jsonb, false, 185, null, 235, 225, 'Mon-Wed and Fri', '["Couples","Families","Individuals"]'::jsonb, '["CBT","ART","REBT","Psychodrama","Experiential"]'::jsonb, '["Anxiety","Grief","Trauma","Self-esteem","Substance Abuse/Addiction","Divorce/Separation","Womens Issues","Postpartum","Motherhood"]'::jsonb, '', 'Not Accepting', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('ashe', 'Ashe Sullivan', 'Ashe Sullivan, LMHC', 'therapy', '["Tampa"]'::jsonb, false, 185, null, null, 235, 'Mon-Fri', '["Minors","Families","Individuals"]'::jsonb, '["CBT","DBT","Mindfulness-Based Therapy","Walk and Talk Therapy","Polyvagal Therapy"]'::jsonb, '["Depression","Anxiety","Grief","Trauma","OCD","Eating Disorders","Body Image","Self-esteem","ADHD","ASD","Substance Abuse/Addiction","LGBTQIA+","Abuse/DV","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Mens Issues","Maternal Health"]'::jsonb, 'Experienced with high-risk suicidal ideation and LGBTQ+ issues. Min age 6.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('alyssa', 'Alyssa Merryman', 'Alyssa Merryman, RMHCI', 'therapy', '["Tyrone"]'::jsonb, false, null, '$100-$150 (sliding scale)', null, null, 'Mon, Tues, Thurs', '["Minors","Individuals"]'::jsonb, '["CBT","DBT","Art Therapy","Mindfulness-Based Therapy"]'::jsonb, '["Anxiety","Depression","OCD","Body Image","Self-esteem","ADHD"]'::jsonb, 'Sliding scale $100-$150. Prefers adolescents and young adults. Min age 10.', 'Needs Clients', 'Low Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('kevin', 'Kevin Curtin', 'Kevin Curtin, RMHCI', 'therapy', '["Tyrone"]'::jsonb, false, 185, null, 235, null, 'Mon-Sat', '["Minors","Couples","Individuals"]'::jsonb, '["CBT","DBT","Art Therapy","Mindfulness-Based Therapy","Psychodynamic","Existential-Humanistic","Narrative","Movement/Flow Therapy"]'::jsonb, '["Anxiety","Depression","BPD","OCD","Bipolar","Self-esteem","ADHD","Substance Abuse/Addiction","Mens Issues","Grief","Spirituality","Sports Psychology"]'::jsonb, 'Works best with creative/overthinker types. Min age 12.', 'Accepting', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('jasmine', 'Jasmine Klugh', 'Jasmine Klugh, LCSW', 'therapy', '["Sarasota"]'::jsonb, false, 185, null, 235, 235, 'Tues-Fri', '["Minors","Couples","Families","Individuals"]'::jsonb, '["CBT","Walk and Talk Therapy"]'::jsonb, '["Anxiety","Depression","Bipolar","Body Image","Self-esteem","ADHD","ASD","Divorce/Separation","Suicidal Ideation","Self-harm","Womens Issues","School Issues","Sports Performance"]'::jsonb, 'Min age 4.', 'Accepting', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('christopher', 'Christopher Rhodes', 'Christopher Rhodes, LMHC', 'therapy', '["Tampa"]'::jsonb, false, 185, null, 235, null, 'Mon-Fri', '["Couples","Minors","Individuals"]'::jsonb, '["CBT","DBT","Gottman Couples Therapy","Mindfulness-Based Therapy","Positive Psychology","Person Centered Therapy"]'::jsonb, '["Anxiety","Depression","Trauma","Self-esteem","LGBTQIA+","Divorce/Separation","Mens Issues","Grief","Sexual Dysfunction","Midlife Crisis"]'::jsonb, 'Open to most clients. Above are preferences. Min age 16.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('albena', 'Albena Christova', 'Albena Christova, LMHC', 'therapy', '["Tyrone"]'::jsonb, false, 185, null, 235, 235, 'Mon-Fri', '["Couples","Families","Individuals"]'::jsonb, '["CBT","Walk and Talk Therapy","Solution Focused Therapy"]'::jsonb, '["Anxiety","Depression","Self-esteem","Bipolar","Divorce/Separation","Womens Issues","Stress Management","Life Transitions"]'::jsonb, '', 'Accepting', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('amanda', 'Amanda Glatthaar', 'Amanda Glatthaar, RMHCI', 'therapy', '["DTSP"]'::jsonb, false, 185, null, null, null, 'Mon-Fri', '["Individuals"]'::jsonb, '["CBT","DBT","ACT","Walk and Talk Therapy","Psychodynamic"]'::jsonb, '["Anxiety","Depression","Grief","Bipolar","BPD","Self-esteem","Substance Abuse/Addiction","LGBTQIA+","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Trauma","Infertility"]'::jsonb, 'Sliding scale available ($150). Open to most clients.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('anna', 'Anna Kitsos', 'Anna Kitsos, LMHC', 'therapy', '["DTSP"]'::jsonb, false, 185, null, 235, 235, 'Mon-Fri', '["Couples","Families"]'::jsonb, '["CBT","DBT","ACT","EFT","Mindfulness-Based Therapy","Walk and Talk Therapy","Motivational Interviewing","Attachment-Based Therapy","Psychodynamic","Polyvagal","TF-CBT","IFS"]'::jsonb, '["Anxiety","Depression","Trauma","Bipolar","BPD","Self-esteem","Substance Abuse/Addiction","Abuse/DV","Divorce/Separation","Self-harm","Suicidal Ideation","Womens Issues","Childhood Trauma"]'::jsonb, 'Sliding scale available.', 'Needs Clients', 'Medium Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('jamilah', 'Jamilah Tulloch', 'Jamilah Tulloch, PMHNP, BC', 'psychiatry', '["Virtual"]'::jsonb, true, null, '$195 follow-up / $390 eval', null, null, 'Sat-Mon', '["Individuals"]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Insurance: Aetna, Cigna, United, BCBS MA, Carelon, Oscar, Oxford, UHC, Horizon BCBS NJ, Independence BCBS PA. Adults only. No Substance Abuse Disorder. No Schizophrenia. VIRTUAL ONLY.', 'Accepting', 'Low Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('amy', 'Amy Wiley', 'Amy Wiley, APRN, PMHNP-BC', 'psychiatry', '["Virtual"]'::jsonb, true, null, '$195 follow-up / $390 eval', null, null, 'Tues-Fri', '["Individuals"]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Insurance: Aetna, Cigna, United, BCBS MA, Carelon, Oscar, Oxford, UHC, Horizon BCBS NJ, Independence BCBS PA. Adults only. No Substance Abuse Disorder. No Schizophrenia. VIRTUAL ONLY.', 'Needs Clients', 'High Priority');
insert into public.clinicians (id, name, profile, type, offices, virtual, indiv, "indivDisplay", couples, family, schedule, groups, modalities, specialties, notes, accepting, priority) values ('lena', 'Lena Allos', 'Lena Allos, PMHNP', 'psychiatry', '["Tyrone","Virtual"]'::jsonb, true, null, '$195 follow-up / $390 eval', null, null, 'Mon virtual, Tues virtual & in-person (Tyrone)', '["Individuals"]'::jsonb, '[]'::jsonb, '[]'::jsonb, 'Insurance: Aetna, Cigna. Sees children 6+. Tuesdays in-office at Tyrone.', 'Needs Clients', 'High Priority');
